---
output:
  md_document:
    variant: gfm
html_preview: false
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r echo=FALSE, results="hide", message=FALSE}
require(badger)
```

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# `R2GUESS`

<!-- badges: start -->
<!-- For the R CMD checks, run usethis::use_github_actions() to set up the pipeline, possibly modify the .yaml file and then: -->
`r badge_license("GPL v3", url = "https://www.gnu.org/licenses/gpl-3.0")`
`r badge_devel("hruffieux/R2GUESS", "blue")`
`r badge_code_size("hruffieux/R2GUESS")`
<!-- badges: end -->

`R2GUESS` provides wrapper functions for GUESS, a GPU-accelerated sparse Bayesian variable selection method for linear regression based analysis of multivariate, correlated outcomes.

## Installation

You can install the development version of `R2GUESS` with:

``` r
if(!require(remotes)) install.packages("remotes")
remotes::install_github("hruffieux/R2GUESS")
```
